version: '3'

services:
  experiment-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./ssl:/app/ssl
      - ./public:/app/public
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Uncomment these lines if you want to set memory/CPU limits
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G

volumes:
  uploads:
    driver: local